# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f12f0edc9624ecb257bc3637ef7ff2a1b85500091ee6e40f0092d10b6876c56303a099d649ff27b133fe28865a60b1e52e1035d6f7cb35f74880a57ca7c383b

test:
  secret_key_base: 75757e9777618138fde0b563ae4fcbc6f20f63daec2bbf78c998a45307077d1ce27432d2720bcd51ae98b1f313fddaafcf175669b6e2b23f803397c97830f4f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
